# Generated by Django 3.2.7 on 2021-09-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
